# Generated by Django 5.0 on 2024-08-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('duration', models.DurationField()),
                ('now', models.DateTimeField()),
                ('index', models.IntegerField()),
            ],
        ),
    ]
